title: tfroment documentation using just the docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tfroment.sandbox-just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/tfroment/sandbox-just-the-docs
  
exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - Gemfile
   - Gemfile.lock
   - README.md

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/komyu.png"

