title: tfroment documentation using just the docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tfroment.sandbox-just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/tfroment/sandbox-just-the-docs
  
